// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Intro Section documents */
type IntroSectionDocumentData = Record<string, never>;
/**
 * Intro Section document from Prismic
 *
 * - **API ID**: `intro_section`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IntroSectionDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<IntroSectionDocumentData>, "intro_section", Lang>;
export type AllDocumentTypes = IntroSectionDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { IntroSectionDocumentData, IntroSectionDocument, AllDocumentTypes };
    }
}
