// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home page documents */
interface HomePageDocumentData {
    /**
     * Slice Zone field in *Home page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomePageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Home page → Slice Zone*
 *
 */
type HomePageDocumentDataSlicesSlice = IntroSectionSlice | AboutSectionSlice;
/**
 * Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomePageDocumentData>, "home_page", Lang>;
export type AllDocumentTypes = HomePageDocument;
/**
 * Primary content in AboutSection → Primary
 *
 */
interface AboutSectionSliceDefaultPrimary {
    /**
     * subtitle field in *AboutSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_section.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * title field in *AboutSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * about us description field in *AboutSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_section.primary.about_us_description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    about_us_description: prismicT.RichTextField;
    /**
     * about us image field in *AboutSection → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: about_section.primary.about_us_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    about_us_image: prismicT.ImageField<never>;
    /**
     * primary button field in *AboutSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_section.primary.primary_button
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    primary_button: prismicT.KeyTextField;
    /**
     * secondary button field in *AboutSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_section.primary.secondary_button
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    secondary_button: prismicT.KeyTextField;
}
/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `AboutSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AboutSectionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *AboutSection*
 *
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;
/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: `AboutSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSectionSlice = prismicT.SharedSlice<"about_section", AboutSectionSliceVariation>;
/**
 * Primary content in IntroSection → Primary
 *
 */
interface IntroSectionSliceDefaultPrimary {
    /**
     * Title field in *IntroSection → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: JONNYONTHESPOT
     * - **API ID Path**: intro_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Subtitle field in *IntroSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: on the spot bartending for wed...
     * - **API ID Path**: intro_section.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    subtitle: prismicT.RichTextField;
    /**
     * Primary button field in *IntroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: intro_section.primary.primary_button
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    primary_button: prismicT.KeyTextField;
    /**
     * Secondary button field in *IntroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: intro_section.primary.secondary_button
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    secondary_button: prismicT.KeyTextField;
    /**
     * Video background field in *IntroSection → Primary*
     *
     * - **Field Type**: Link to Media
     * - **Placeholder**: *None*
     * - **API ID Path**: intro_section.primary.video_background
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    video_background: prismicT.LinkToMediaField;
}
/**
 * Item in IntroSection → Items
 *
 */
export interface IntroSectionSliceDefaultItem {
    /**
     * Summarized service field in *IntroSection → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: e.g. Cocktails, parties, weddings
     * - **API ID Path**: intro_section.items[].summarized_service
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    summarized_service: prismicT.RichTextField;
}
/**
 * Default variation for IntroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `IntroSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IntroSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<IntroSectionSliceDefaultPrimary>, Simplify<IntroSectionSliceDefaultItem>>;
/**
 * Slice variation for *IntroSection*
 *
 */
type IntroSectionSliceVariation = IntroSectionSliceDefault;
/**
 * IntroSection Shared Slice
 *
 * - **API ID**: `intro_section`
 * - **Description**: `IntroSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type IntroSectionSlice = prismicT.SharedSlice<"intro_section", IntroSectionSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomePageDocumentData, HomePageDocumentDataSlicesSlice, HomePageDocument, AllDocumentTypes, AboutSectionSliceDefaultPrimary, AboutSectionSliceDefault, AboutSectionSliceVariation, AboutSectionSlice, IntroSectionSliceDefaultPrimary, IntroSectionSliceDefaultItem, IntroSectionSliceDefault, IntroSectionSliceVariation, IntroSectionSlice };
    }
}
