// Code generated by Slice Machine. DO NOT EDIT.

import AboutSection from './AboutSection';
import ContactSection from './ContactSection';
import GallerySection from './GallerySection';
import IntroSection from './IntroSection';
import PriceSection from './PriceSection';
import ServicesSection from './ServicesSection';
import TestimonialSection from './TestimonialSection';

export {
	AboutSection,
	ContactSection,
	GallerySection,
	IntroSection,
	PriceSection,
	ServicesSection,
	TestimonialSection,
};

export const components = {
	about_section: AboutSection,
	contact_section: ContactSection,
	gallery_section: GallerySection,
	intro_section: IntroSection,
	price_section: PriceSection,
	services_section: ServicesSection,
	testimonial_section: TestimonialSection,
};
